import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Weight } from "lucide-react";

// Header components : 
import Header from "@/components/layout/Header";
import PageTransition from "@/components/layout/PageTransition";

const jetBrains_Mono = JetBrains_Mono({ 
	subsets: ["latin"] ,
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	variable: "--font-jetbrainsMono"
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={jetBrains_Mono.variable}>
				<Header/>

				<PageTransition>
					{children}
				</PageTransition>

			</body>
		</html>
	);
}
